<template>
  <div>
    <form action="">
      <div id="title">
        <p>Titel</p>
        <input type="text">
      </div>
      <div id="Author">
        <p>Författre</p>
        <input type="text">
      </div>
      <div id="format">

      </div>
      <div id="genres">
        <p>Genres</p>
        <select name="countries" id="countries" multiple>
          <option value="1">Afghanistan</option>
          <option value="2">Australia</option>
          <option value="3">Germany</option>
          <option value="4">Canada</option>
          <option value="5">Russia</option>
      </select>

      </div>
      <input type="">
    </form>
  </div>
</template>