<template>
    <div>
        <div class="p-3">
            <div>
                <p class="text-center font-bold text-lg ">Registrera dig</p>
            </div>
            <form action="">
                <div class="p-1">
                    <div>Namn</div>
                    <input type="name" placeholder="skriv ditt namn här" class="w-full">
                </div>
                <div class="p-1">
                    <div>Email</div>
                    <input type=" email" placeholder="skriv din Email här" class="w-full">
                </div>
                <div class="p-1">
                    <div>Lösenord</div>
                    <input type=" password" placeholder="skriv ditt lösenord här" class="w-full">
                    <input type=" password" placeholder="Confrimera ditt lösenord" class="w-full">
                </div>
                <div class="flex justify-center"><button>Registrera dig</button></div>

            </form>
        </div>
    </div>
</template>